name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y autopoint meson ninja-build gettext libunwind-dev libefl-all-dev libeet1 libeet-bin
        # sudo apt-get install -y check
    - name: project setup (meson)
      run: meson setup . build
    - name: project build (ninja)
      run: ninja -C build
    - name: Codecov
      uses: codecov/codecov-action@v3.1.4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
