name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      # PYTHON: '3.10'
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autopoint meson ninja-build gettext libunwind-dev libefl-all-dev libeet1 libeet-bin
        sudo apt-get install -y check
    - name: Setup python
      uses: actions/setup-python@master
      # with:
      #   python-version: 3.10
    - name: Install coverage
      run: pip install coverage
    - name: Setup project (meson)
      run: meson setup . build -Db_coverage=true
    - name: Buil project (ninja)
      run: ninja -C build
    - name: Generate coverage report
      run: ninja -C build coverage
    - name: Upload to Codecov
      uses: codecov/codecov-action@v3.1.4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
